### ISSUE TITLE
New css style for generated tables

### ISSUE THREAD

**Issue by jfoclpf** [jfoclpf/autocosts#97] opened 2019-01-07 22:59 UTC
@mcristaldo 

In our building script there is a subscript to generate html tables for the averages of every country.
Such subscript also generates JPG files from said html tables (jpg files are easier to share around). 

Check [here](https://github.com/jfoclpf/autocosts/tree/master/src/tables) the template for the generation and rendering of these tables. Go also to the `bin/tables` folder in the server (since is the building script, generated files are dumped into `bin/`). 

**Task:** Can you create a style for these tables, following the style we are using? Basically you will just need to edit [here](https://github.com/jfoclpf/autocosts/blob/master/src/tables/template.hbs#L6).

Note that this style must be all embedded in the template file hbs/html, that is, inside `<style></style>` because the template must be a singleton that is used for further rendering the JPG tables. 

Now the tables are being rendering like this:

Image rendered from [this](https://github.com/jfoclpf/autocosts/blob/master/src/tables/template.hbs) html file

![image](https://user-images.githubusercontent.com/3984909/50798032-289a9a00-12d7-11e9-8a05-1c53ad5a1e8b.png)
 
Any question, as usual, let me know.
Thank you

**Comment by mcristaldo** [comment] 2019-01-14 20:32
Hi @jfoclpf 
I just committed the file. Please take a look and let me know if it works properly.

Thank you.

**Comment by jfoclpf** [comment] 2019-01-14 21:31
Hi @mcristaldo 
basically we need to edit this table here, for example
https://autocosts.work/tables/NI.html

Maybe you committed on your local machine, but you didn't push it to this repository.
Check here: https://github.com/jfoclpf/autocosts/commits/master

pull (update) again from this repo to your local machine, before pushing because I made some updates in the meantime, but most likely there's no conflicts

**Comment by jfoclpf** [comment] 2019-01-14 22:41
ok @mcristaldo 

but `commit` and `push` are different commands

when you commit you commit to your local repository, you create a `commit`, but then you have to push your local commits to the repo here on github, that is, on the cloud. 

Are you suing git in command line or any piece of SW?

**Comment by mcristaldo** [comment] 2019-01-15 13:59
Yes but when I try to "Pull origin" I'm always getting a conflict in a
file:
https://www.dropbox.com/s/5g7v2anwef8hnzr/Captura%20de%20pantalla%202019-01-15%2010.56.13.png?dl=0

Even though I already commited the template.hbs file on the Github website,
it came up with conflicts, it add weird characters in the code. I will need
to re-upload it. Idk Github desktop is not working well OR I'm not
understanding what the problem is.

Martín Cristaldo UI/UX designer
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
www.mct.uy
Dribbble: m_cristaldo <https://dribbble.com/m_cristaldo>
Twitter: @m_cristaldo <https://twitter.com/m_cristaldo>
Instagram: mctuy <https://instagram.com/mctuy/>
Blog: @mcristaldo <https://medium.com/@mcristaldo>

**Comment by jfoclpf** [comment] 2019-01-15 18:43
I see. Conflicts appear when two people worked separately on the same file
on the same part of the code, because git cannot then merge.

Kindly read

https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/

I know, github is complex and perhaps a hassle for the 1st time, but
believe me it's an add-on in your knowledge which you won't regret.

Could you kindly read the article and try to resolve the conflicts? Kindly
do not charge the article reading. I see that you can open a text editor.

**Comment by jfoclpf** [comment] 2019-01-16 21:58
I see you could do it, thanks. I had to correct some html errors.

Nonetheless check the generated table
https://autocosts.work/tables/US.html

could you align the table?

and errors on the html still continue. Can you solve this errors?
https://validator.w3.org/nu/?doc=https%3A%2F%2Fautocosts.work%2Ftables%2FUS.html

**Comment by mcristaldo** [comment] 2019-01-17 17:34
Hi Joao, 
I just fixed the alignment issues. I will check the HTML errors.

**Comment by mcristaldo** [comment] 2019-01-17 18:36
Just solved HTML errors on template.hbs file

**Closed** 2019-02-04 13:53 UTC
Labels: newUI
